"""Initial models

Revision ID: ad51b7cf1c91
Revises: 
Create Date: 2025-04-29 16:50:52.905845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ad51b7cf1c91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('smoker', sa.Boolean(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('interval_min', sa.Float(), nullable=False),
    sa.Column('interval_max', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('franchise', sa.Float(), nullable=False),
    sa.Column('ceiling', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refund_estimate', sa.Float(), nullable=False),
    sa.Column('annual_price', sa.Float(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('suggestions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_factors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['modelinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('modelinfo')
    # ### end Alembic commands ###
