"""change model name unique

Revision ID: c65732c65867
Revises: ad51b7cf1c91
Create Date: 2025-05-01 14:26:20.832873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c65732c65867'
down_revision: Union[str, None] = 'ad51b7cf1c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'modelinfo', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modelinfo', type_='unique')
    # ### end Alembic commands ###
